### ISSUE TITLE
Knoten der Site Sankt Augustin werden nicht in DE-Map übernommen

### ISSUE THREAD

**Issue by berwag** [Freifunk-Rhein-Sieg/api-json#1]
In der Datei sankt-augustin.json stimmt die URL im Abschnitt "nodeMaps" nicht mit der Realität überein.

In der Datei:
"http://map.freifunk-rhein-sieg.de/sanktaugustin"

Im Internet:
"http://map.freifunk-rhein-sieg.de/sankt-augustin"

Da https://github.com/freifunk/directory.api.freifunk.net/blob/master/directory.json die Datei sankt-augustin.json referenziert, nehme ich an, dass es über die dort angegebene URL versucht, für die Deutschland-Karte an die Daten zu kommen.

**Comment by stebifan** [comment]
Gefixt
